import Foundation

struct HeightWeightRange {
    let heightMin: Double
    let heightMax: Double
    let weight: Int
    let color: String
}

struct AdultWeightRange {
    let weightMin: Int
    let weightMax: Int
    let color: String
}

struct DosageData {
    static let heightWeightRanges: [HeightWeightRange] = [
        HeightWeightRange(heightMin: 41.4, heightMax: 47.2, weight: 3, color: "grey"),
        HeightWeightRange(heightMin: 47.2, heightMax: 53.3, weight: 4, color: "grey"),
        HeightWeightRange(heightMin: 53.3, heightMax: 58.8, weight: 5, color: "grey"),
        HeightWeightRange(heightMin: 58.8, heightMax: 63.7, weight: 6, color: "pink"),
        HeightWeightRange(heightMin: 63.7, heightMax: 68.3, weight: 7, color: "pink"),
        HeightWeightRange(heightMin: 68.3, heightMax: 72.6, weight: 8, color: "red"),
        HeightWeightRange(heightMin: 72.6, heightMax: 76.6, weight: 9, color: "red"),
        HeightWeightRange(heightMin: 76.6, heightMax: 80.4, weight: 10, color: "purple"),
        HeightWeightRange(heightMin: 80.4, heightMax: 84.1, weight: 11, color: "purple"),
        HeightWeightRange(heightMin: 84.1, heightMax: 87.5, weight: 12, color: "yellow"),
        HeightWeightRange(heightMin: 87.5, heightMax: 90.9, weight: 13, color: "yellow"),
        HeightWeightRange(heightMin: 90.9, heightMax: 94.0, weight: 14, color: "yellow"),
        HeightWeightRange(heightMin: 94.0, heightMax: 97.1, weight: 15, color: "white"),
        HeightWeightRange(heightMin: 97.1, heightMax: 100.1, weight: 16, color: "white"),
        HeightWeightRange(heightMin: 100.1, heightMax: 103.0, weight: 17, color: "white"),
        HeightWeightRange(heightMin: 103.0, heightMax: 105.8, weight: 18, color: "white"),
        HeightWeightRange(heightMin: 105.8, heightMax: 108.6, weight: 19, color: "blue"),
        HeightWeightRange(heightMin: 108.6, heightMax: 111.2, weight: 20, color: "blue"),
        HeightWeightRange(heightMin: 111.2, heightMax: 113.8, weight: 21, color: "blue"),
        HeightWeightRange(heightMin: 113.8, heightMax: 116.4, weight: 22, color: "blue"),
        HeightWeightRange(heightMin: 116.4, heightMax: 118.9, weight: 23, color: "blue"),
        HeightWeightRange(heightMin: 118.9, heightMax: 121.2, weight: 24, color: "orange"),
        HeightWeightRange(heightMin: 121.2, heightMax: 123.6, weight: 25, color: "orange"),
        HeightWeightRange(heightMin: 123.6, heightMax: 126.0, weight: 26, color: "orange"),
        HeightWeightRange(heightMin: 126.0, heightMax: 128.3, weight: 27, color: "orange"),
        HeightWeightRange(heightMin: 128.3, heightMax: 130.5, weight: 28, color: "orange"),
        HeightWeightRange(heightMin: 130.5, heightMax: 132.7, weight: 29, color: "orange"),
        HeightWeightRange(heightMin: 132.7, heightMax: 134.8, weight: 30, color: "green"),
        HeightWeightRange(heightMin: 134.8, heightMax: 137.0, weight: 31, color: "green"),
        HeightWeightRange(heightMin: 137.0, heightMax: 139.0, weight: 32, color: "green"),
        HeightWeightRange(heightMin: 139.0, heightMax: 141.1, weight: 33, color: "green"),
        HeightWeightRange(heightMin: 141.1, heightMax: 143.2, weight: 34, color: "green"),
        HeightWeightRange(heightMin: 143.2, heightMax: 145.1, weight: 35, color: "green"),
        HeightWeightRange(heightMin: 145.1, heightMax: 147.2, weight: 36, color: "green"),
        HeightWeightRange(heightMin: 147.2, heightMax: 149.1, weight: 37, color: "green")
    ]

    static let adultWeightRanges: [AdultWeightRange] = [
        AdultWeightRange(weightMin: 37, weightMax: 45, color: "orange"),
        AdultWeightRange(weightMin: 46, weightMax: 55, color: "green"),
        AdultWeightRange(weightMin: 56, weightMax: 65, color: "blue"),
        AdultWeightRange(weightMin: 66, weightMax: Int.max, color: "purple")
    ]

    static func getColorForHeight(_ height: Double) -> String {
        for range in heightWeightRanges {
            if height >= range.heightMin && height < range.heightMax {
                return range.color
            }
        }
        return "grey"
    }
    
    static func getColorForWeight(_ weight: Double) -> String {
        switch weight {
        case 3..<6:
            return "grey"
        case 6..<8:
            return "pink"
        case 8..<10:
            return "red"
        case 10..<12:
            return "purple"
        case 12..<15:
            return "yellow"
        case 15..<19:
            return "white"
        case 19..<24:
            return "blue"
        case 24..<30:
            return "orange"
        case 30..<37:
            return "green"
        case 37..<46:
            return "greenDot"
        case 46..<56:
            return "blueDot"
        case 56..<66:
            return "orangeDot"
        case 66...:
            return "lightBlueDot"
        default:
            return "grey"
        }
    }
    
    static let dosageMap: [String: [String: String]] = [
        "grey": [
            "Miller_Blade": "1",
            "Mac_Blade": "1",
            "Airtraq": "0",
            "VividTrac": "",
            "Endotracheal_Tube_Cuffed": "2.5-3.0",
            "LMA": "1",
            "KingTube": "0-1",
            "iGel": "1",
            "Etomidate_IV_IO": "1.2 mg/0.6mL",
            "Ketamine_IV_IO": "10 mg/0.2mL",
            "Succinylcholine_IV_IO": "8 mg/0.4 mL",
            "Rocuronium_IV_IO": "5 mg/0.5 mL",
            "Fentanyl_IV_IO": "5 mcg/0.1 mL",
            "Midazolam_IV_IO": "0.5 mg/0.1 mL",
            "Lorazepam_IV_IO": "0.4 mg/0.2 mL",
            "shock_1st": "8 J",
            "shock_2nd": "16 J",
            "shock_3rd": "16 - 50 J",
            "Epinephrine_1mg_10mL_IV": "0.05 mg/0.5 mL",
            "Atropine_IV_IO_ETT": "0.1 mg/1 mL",
            "Magnesium_sulfate_IV": "150 mg/0.3 mL",
            "Epinephrine_1mg_1mL_ETT": "0.5 mg/0.5mL",
            "Amiodarone_IV": "20 mg/0.4mL",
            "Lidocaine_IV": "4 mg/0.2 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "0.4 mcg/min (6 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "4 mcg/min (60 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.1 mg/0.1 mL",
            "Diphenhydramine_IV_IM": "5 mg/0.1 mL",
            "Famotidine_IV": "2 mg/0.2 mL",
            "Methylprednisolone_IV": "6.3 mg/0.1 mL",
            "Fentanyl_IN": "5 mcg/0.1 mL",
            "Fentanyl_IV": "5 mcg/0.1 mL",
            "Ketorolac_IV": "",
            "Tylenol_PO": "60 mg/1.9 mL",
            "Ibuprofen_PO": "",
            "Midazolam_IN": "1 mg/0.2 mL",
            "Midazolam_IV": "0.5 mg/0.1 mL",
            "Lorazepam_IV": "0.4 mg/0.2 mL",
            "D10_IV": "12 mL"
        ],
        "pink": [
            "Miller_Blade": "1",
            "Mac_Blade": "1",
            "Airtraq": "0",
            "VividTrac": "",
            "Endotracheal_Tube_Cuffed": "3.0-3.5",
            "LMA": "1.5",
            "KingTube": "1",
            "iGel": "1.5",
            "Etomidate_IV_IO": "2 mg/1 mL",
            "Ketamine_IV_IO": "15 mg/0.3 mL",
            "Succinylcholine_IV_IO": "14 mg/0.7 mL",
            "Rocuronium_IV_IO": "6 mg/0.6 mL",
            "Fentanyl_IV_IO": "5 mcg/0.1 mL",
            "Midazolam_IV_IO": "0.5 mg/0.1 mL",
            "Lorazepam_IV_IO": "0.6 mg/0.3 mL",
            "shock_1st": "14 J",
            "shock_2nd": "28 J",
            "shock_3rd": "18 - 70 J",
            "Epinephrine_1mg_10mL_IV": "0.07 mg/0.7 mL",
            "Atropine_IV_IO_ETT": "0.12 mg/1.2 mL",
            "Magnesium_sulfate_IV": "250 mg/0.5 mL",
            "Epinephrine_1mg_1mL_ETT": "0.7 mg/0.7 mL",
            "Amiodarone_IV": "35 mg/0.7 mL",
            "Lidocaine_IV": "6 mg/0.3 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "0.6 mcg/min (9 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "6 mcg/min (90 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.1 mg/0.1 mL",
            "Diphenhydramine_IV_IM": "5 mg/0.1 mL",
            "Famotidine_IV": "4 mg/0.4 mL",
            "Methylprednisolone_IV": "12.5 mg/0.2 mL",
            "Fentanyl_IN": "10 mcg/0.2 mL",
            "Fentanyl_IV": "5 mcg/0.1 mL",
            "Ketorolac_IV": "3 mg/0.1 mL",
            "Tylenol_PO": "90 mg/2.8 mL",
            "Ibuprofen_PO": "60 mg/3 mL",
            "Midazolam_IN": "1.5 mg/0.3 mL",
            "Midazolam_IV": "1 mg/0.2 mL",
            "Lorazepam_IV": "0.6 mg/0.3 mL",
            "D10_IV": "20 mL"
        ],
        "red": [
            "Miller_Blade": "1",
            "Mac_Blade": "1",
            "Airtraq": "0",
            "VividTrac": "Peds",
            "Endotracheal_Tube_Cuffed": "3.5-4.0",
            "LMA": "1.5",
            "KingTube": "1",
            "iGel": "1.5",
            "Etomidate_IV_IO": "2.6 mg/1.3 mL",
            "Ketamine_IV_IO": "15 mg/0.3 mL",
            "Succinylcholine_IV_IO": "18 mg/0.9 mL",
            "Rocuronium_IV_IO": "8 mg/0.8 mL",
            "Fentanyl_IV_IO": "10 mcg/0.2 mL",
            "Midazolam_IV_IO": "1 mg/0.2 mL",
            "Lorazepam_IV_IO": "0.8 mg/0.4 mL",
            "shock_1st": "18 J",
            "shock_2nd": "36 J",
            "shock_3rd": "36 - 90 J",
            "Epinephrine_1mg_10mL_IV": "0.09 mg/0.9 mL",
            "Atropine_IV_IO_ETT": "0.18 mg/1.8 mL",
            "Magnesium_sulfate_IV": "350 mg/0.7 mL",
            "Epinephrine_1mg_1mL_ETT": "0.9 mg/0.9 mL",
            "Amiodarone_IV": "45 mg/0.9 mL",
            "Lidocaine_IV": "8 mg/0.4 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "0.8 mcg/min (12 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "8 mcg/min (120 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.1 mg/0.1 mL",
            "Diphenhydramine_IV_IM": "10 mg/0.2 mL",
            "Famotidine_IV": "5 mg/0.5 mL",
            "Methylprednisolone_IV": "19 mg/0.3 mL",
            "Fentanyl_IN": "15 mcg/0.3 mL",
            "Fentanyl_IV": "10 mcg/0.2 mL",
            "Ketorolac_IV": "3 mg/0.1 mL",
            "Tylenol_PO": "120 mg/3.8 mL",
            "Ibuprofen_PO": "80 mg/4 mL",
            "Midazolam_IN": "2 mg/0.4 mL",
            "Midazolam_IV": "1 mg/0.2 mL",
            "Lorazepam_IV": "0.8 mg/0.4 mL",
            "D10_IV": "26 mL"
        ],
        "purple": [
            "Miller_Blade": "2",
            "Mac_Blade": "2",
            "Airtraq": "1",
            "VividTrac": "Peds",
            "Endotracheal_Tube_Cuffed": "3.5-4.0",
            "LMA": "2",
            "KingTube": "1",
            "iGel": "1.5-2",
            "Etomidate_IV_IO": "3.2 mg/1.6 mL",
            "Ketamine_IV_IO": "20 mg/0.4 mL",
            "Succinylcholine_IV_IO": "20 mg/1 mL",
            "Rocuronium_IV_IO": "10 mg/1 mL",
            "Fentanyl_IV_IO": "10 mcg/0.2 mL",
            "Midazolam_IV_IO": "1 mg/0.2 mL",
            "Lorazepam_IV_IO": "1 mg/0.5 mL",
            "shock_1st": "22 J",
            "shock_2nd": "44 J",
            "shock_3rd": "44 - 110 J",
            "Epinephrine_1mg_10mL_IV": "0.1 mg/1 mL",
            "Atropine_IV_IO_ETT": "0.2 mg/2 mL",
            "Magnesium_sulfate_IV": "400 mg/0.8 mL",
            "Epinephrine_1mg_1mL_ETT": "1 mg/1 mL",
            "Amiodarone_IV": "55 mg/1.1 mL",
            "Lidocaine_IV": "10 mg/0.5 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "1 mcg/min (15 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "10 mcg/min (150 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.1 mg/0.1 mL",
            "Diphenhydramine_IV_IM": "10 mg/0.2 mL",
            "Famotidine_IV": "6 mg/0.6 mL",
            "Methylprednisolone_IV": "19 mg/0.3 mL",
            "Fentanyl_IN": "15 mcg/0.3 mL",
            "Fentanyl_IV": "10 mcg/0.2 mL",
            "Ketorolac_IV": "3 mg/0.1 mL",
            "Tylenol_PO": "150 mg/4.7 mL",
            "Ibuprofen_PO": "100 mg/5 mL",
            "Midazolam_IN": "2 mg/0.4 mL",
            "Midazolam_IV": "1 mg/0.2 mL",
            "Lorazepam_IV": "0.8 mg/0.4 mL",
            "D10_IV": "32 mL"
        ],
        "yellow": [
            "Miller_Blade": "2",
            "Mac_Blade": "2",
            "Airtraq": "1",
            "VividTrac": "Peds",
            "Endotracheal_Tube_Cuffed": "4.0-4.5",
            "LMA": "2",
            "KingTube": "2",
            "iGel": "2",
            "Etomidate_IV_IO": "4 mg/2 mL",
            "Ketamine_IV_IO": "25 mg/0.5 mL",
            "Succinylcholine_IV_IO": "26 mg/1.3 mL",
            "Rocuronium_IV_IO": "12 mg/1.2 mL",
            "Fentanyl_IV_IO": "15 mcg/0.3 mL",
            "Midazolam_IV_IO": "1.5 mg/0.3 mL",
            "Lorazepam_IV_IO": "1.2 mg/0.6 mL",
            "shock_1st": "25 J",
            "shock_2nd": "50 J",
            "shock_3rd": "50 - 140 J",
            "Epinephrine_1mg_10mL_IV": "0.13 mg/1.3 mL",
            "Atropine_IV_IO_ETT": "0.25 mg/2.5 mL",
            "Magnesium_sulfate_IV": "500 mg/1 mL",
            "Epinephrine_1mg_1mL_ETT": "1.3 mg/1.3 mL",
            "Amiodarone_IV": "65 mg/1.3 mL",
            "Lidocaine_IV": "12 mg/0.6 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "1.2 mcg/min (18 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "10 mcg/min (150 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.1 mg/0.1 mL",
            "Diphenhydramine_IV_IM": "15 mg/0.3 mL",
            "Famotidine_IV": "7 mg/0.7 mL",
            "Methylprednisolone_IV": "25 mg/0.4 mL",
            "Fentanyl_IN": "20 mcg/0.4 mL",
            "Fentanyl_IV": "15 mcg/0.3 mL",
            "Ketorolac_IV": "6 mg/0.2 mL",
            "Tylenol_PO": "180 mg/5.6 mL",
            "Ibuprofen_PO": "140 mg/7 mL",
            "Midazolam_IN": "2.5 mg/0.5 mL",
            "Midazolam_IV": "1.5 mg/0.3 mL",
            "Lorazepam_IV": "1.2 mg/0.6 mL",
            "D10_IV": "39 mL"
        ],
        "white": [
            "Miller_Blade": "2",
            "Mac_Blade": "2",
            "Airtraq": "1",
            "VividTrac": "Peds",
            "Endotracheal_Tube_Cuffed": "4.5-5.0",
            "LMA": "2",
            "KingTube": "2",
            "iGel": "2",
            "Etomidate_IV_IO": "5 mg/2.5 mL",
            "Ketamine_IV_IO": "30 mg/0.6 mL",
            "Succinylcholine_IV_IO": "32 mg/1.6 mL",
            "Rocuronium_IV_IO": "16 mg/1.6 mL",
            "Fentanyl_IV_IO": "15 mcg/0.3 mL",
            "Midazolam_IV_IO": "2 mg/0.4 mL",
            "Lorazepam_IV_IO": "1.6 mg/0.8 mL",
            "shock_1st": "35 J",
            "shock_2nd": "70 J",
            "shock_3rd": "70 - 160 J",
            "Epinephrine_1mg_10mL_IV": "0.15 mg/1.5 mL",
            "Atropine_IV_IO_ETT": "0.35 mg/3.5 mL",
            "Magnesium_sulfate_IV": "650 mg/1.3 mL",
            "Epinephrine_1mg_1mL_ETT": "1.5 mg/1.5 mL",
            "Amiodarone_IV": "85 mg/1.7 mL",
            "Lidocaine_IV": "16 mg/0.8 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "1.6 mcg/min (24 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "10 mcg/min (150 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.2 mg/0.2 mL",
            "Diphenhydramine_IV_IM": "15 mg/0.3 mL",
            "Famotidine_IV": "8 mg/0.8 mL",
            "Methylprednisolone_IV": "31 mg/0.5 mL",
            "Fentanyl_IN": "25 mcg/0.5 mL",
            "Fentanyl_IV": "15 mcg/0.3 mL",
            "Ketorolac_IV": "9 mg/0.3 mL",
            "Tylenol_PO": "240 mg/7.5 mL",
            "Ibuprofen_PO": "160 mg/8 mL",
            "Midazolam_IN": "3 mg/0.6 mL",
            "Midazolam_IV": "2 mg/0.4 mL",
            "Lorazepam_IV": "1.6 mg/0.8 mL",
            "D10_IV": "50 mL"
        ],
        "blue": [
            "Miller_Blade": "2",
            "Mac_Blade": "2",
            "Airtraq": "1",
            "VividTrac": "Peds",
            "Endotracheal_Tube_Cuffed": "5.0-5.5",
            "LMA": "2.5",
            "KingTube": "2",
            "iGel": "2",
            "Etomidate_IV_IO": "6.2 mg/3.1 mL",
            "Ketamine_IV_IO": "40 mg/0.8 mL",
            "Succinylcholine_IV_IO": "42 mg/2.1 mL",
            "Rocuronium_IV_IO": "21 mg/2.1 mL",
            "Fentanyl_IV_IO": "20 mcg/0.4 mL",
            "Midazolam_IV_IO": "2 mg/0.4 mL",
            "Lorazepam_IV_IO": "2 mg/2 mL",
            "shock_1st": "45 J",
            "shock_2nd": "90 J",
            "shock_3rd": "90 - 200 J",
            "Epinephrine_1mg_10mL_IV": "0.2 mg/2 mL",
            "Atropine_IV_IO_ETT": "0.4 mg/4 mL",
            "Magnesium_sulfate_IV": "850 mg/1.7 mL",
            "Epinephrine_1mg_1mL_ETT": "2 mg/2 mL",
            "Amiodarone_IV": "105 mg/2.1 mL",
            "Lidocaine_IV": "20 mg/1 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "2 mcg/min (30 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "10 mcg/min (150 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.2 mg/0.2 mL",
            "Diphenhydramine_IV_IM": "20 mg/0.4 mL",
            "Famotidine_IV": "10 mg/1 mL",
            "Methylprednisolone_IV": "44 mg/0.7 mL",
            "Fentanyl_IN": "35 mcg/0.7 mL",
            "Fentanyl_IV": "25 mcg/0.5 mL",
            "Ketorolac_IV": "15 mg/0.5 mL",
            "Tylenol_PO": "325 mg/1 tab",
            "Ibuprofen_PO": "200 mg/1 tab",
            "Midazolam_IN": "4.5 mg/0.9 mL",
            "Midazolam_IV": "2 mg/0.4 mL",
            "Lorazepam_IV": "2 mg/1 mL",
            "D10_IV": "63 mL"
        ],
        "orange": [
            "Miller_Blade": "2",
            "Mac_Blade": "2-3",
            "Airtraq": "2",
            "VividTrac": "Adult",
            "Endotracheal_Tube_Cuffed": "6",
            "LMA": "2.5",
            "KingTube": "2.5",
            "iGel": "2.5",
            "Etomidate_IV_IO": "8 mg/4 mL",
            "Ketamine_IV_IO": "50 mg/1 mL",
            "Succinylcholine_IV_IO": "50 mg/2.5 mL",
            "Rocuronium_IV_IO": "25 mg/2.5 mL",
            "Fentanyl_IV_IO": "25 mcg/0.5 mL",
            "Midazolam_IV_IO": "2.5 mg/0.5 mL",
            "Lorazepam_IV_IO": "2 mg/2 mL",
            "shock_1st": "55 J",
            "shock_2nd": "110 J",
            "shock_3rd": "110 - 200 J",
            "Epinephrine_1mg_10mL_IV": "0.25 mg/2.5 mL",
            "Atropine_IV_IO_ETT": "0.5 mg/5 mL",
            "Magnesium_sulfate_IV": "1 gm/2 mL",
            "Epinephrine_1mg_1mL_ETT": "2.5 mg/2.5 mL",
            "Amiodarone_IV": "135 mg/2.7 mL",
            "Lidocaine_IV": "26 mg/1.3 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "2.7 mcg/min (40 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "10 mcg/min (150 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.3 mg/0.3 mL",
            "Diphenhydramine_IV_IM": "25 mg/0.5 mL",
            "Famotidine_IV": "13 mg/1.3 mL",
            "Methylprednisolone_IV": "50 mg/0.8 mL",
            "Fentanyl_IN": "40 mcg/0.8 mL",
            "Fentanyl_IV": "25 mcg/0.5 mL",
            "Ketorolac_IV": "15 mg/0.5 mL",
            "Tylenol_PO": "325 mg/1 tab",
            "Ibuprofen_PO": "200 mg/1 tab",
            "Midazolam_IN": "5.5 mg/1.1 mL",
            "Midazolam_IV": "2.5 mg/0.5 mL",
            "Lorazepam_IV": "2 mg/1 mL",
            "D10_IV": "84 mL"
        ],
        "green": [
            "Miller_Blade": "2",
            "Mac_Blade": "2-3",
            "Airtraq": "2",
            "VividTrac": "Adult",
            "Endotracheal_Tube_Cuffed": "6.0-6.5",
            "LMA": "3",
            "KingTube": "3",
            "iGel": "2.5-3",
            "Etomidate_IV_IO": "10 mg/5 mL",
            "Ketamine_IV_IO": "60 mg/1.2 mL",
            "Succinylcholine_IV_IO": "60 mg/3 mL",
            "Rocuronium_IV_IO": "30 mg/3 mL",
            "Fentanyl_IV_IO": "35 mcg/0.7 mL",
            "Midazolam_IV_IO": "3.5 mg/0.7 mL",
            "Lorazepam_IV_IO": "2 mg/2 mL",
            "shock_1st": "65 J",
            "shock_2nd": "130 J",
            "shock_3rd": "130 - 200 J",
            "Epinephrine_1mg_10mL_IV": "0.35 mg/3.5 mL",
            "Atropine_IV_IO_ETT": "0.5 mg/5 mL",
            "Magnesium_sulfate_IV": "1.4 gm/2.8 mL",
            "Epinephrine_1mg_1mL_ETT": "2.5 mg/2.5 mL",
            "Amiodarone_IV": "175 mg/3.5 mL",
            "Lidocaine_IV": "34 mg/1.7 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "3.3 mcg/min (50 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "10 mcg/min (150 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.3 mg/0.3 mL",
            "Diphenhydramine_IV_IM": "35 mg/0.7 mL",
            "Famotidine_IV": "17 mg/1.7 mL",
            "Methylprednisolone_IV": "63 mg/1 mL",
            "Fentanyl_IN": "50 mcg/1 mL",
            "Fentanyl_IV": "35 mcg/0.7 mL",
            "Ketorolac_IV": "18 mg/0.6 mL",
            "Tylenol_PO": "325 mg/1 tab",
            "Ibuprofen_PO": "200 mg/1 tab",
            "Midazolam_IN": "7 mg/1.4 mL",
            "Midazolam_IV": "3.5 mg/0.7 mL",
            "Lorazepam_IV": "2 mg/1 mL",
            "D10_IV": "100 mL"
        ],
        "greenDot": [
            "Miller_Blade": "3",
            "Mac_Blade": "2-3",
            "Airtraq": "2",
            "VividTrac": "Adult",
            "Endotracheal_Tube_Cuffed": "6.5",
            "LMA": "3",
            "KingTube": "3",
            "iGel": "3",
            "Etomidate_IV_IO": "12 mg/6 mL",
            "Ketamine_IV_IO": "80 mg/1.6 mL",
            "Succinylcholine_IV_IO": "80 mg/4 mL",
            "Rocuronium_IV_IO": "40 mg/4 mL",
            "Fentanyl_IV_IO": "40 mcg/0.8 mL",
            "Midazolam_IV_IO": "4 mg/0.8 mL",
            "Lorazepam_IV_IO": "2 mg/2 mL",
            "shock_1st": "90 J",
            "shock_2nd": "180 J",
            "shock_3rd": "180 - 200 J",
            "Epinephrine_1mg_10mL_IV": "0.4 mg/4 mL",
            "Atropine_IV_IO_ETT": "0.8 mg/8 mL",
            "Magnesium_sulfate_IV": "1.6 gm/3.2 mL",
            "Epinephrine_1mg_1mL_ETT": "2.5 mg/2.5 mL",
            "Amiodarone_IV": "200 mg/4 mL",
            "Lidocaine_IV": "40 mg/2 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "4 mcg/min (60 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "10 mcg/min (150 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.4 mg/0.4 mL",
            "Diphenhydramine_IV_IM": "40 mg/0.8 mL",
            "Famotidine_IV": "20 mg/2 mL",
            "Methylprednisolone_IV": "81 mg/1.3 mL",
            "Fentanyl_IN": "70 mcg/1.4 mL",
            "Fentanyl_IV": "40 mcg/0.8 mL",
            "Ketorolac_IV": "21 mg/0.7 mL",
            "Tylenol_PO": "487.5 mg/1.5 tab",
            "Ibuprofen_PO": "400 mg/2 tab",
            "Midazolam_IN": "8.5 mg/1.7 mL",
            "Midazolam_IV": "4 mg/0.8 mL",
            "Lorazepam_IV": "2 mg/1 mL",
            "D10_IV": "126 mL"
        ],
        "blueDot": [
            "Miller_Blade": "3",
            "Mac_Blade": "2-3",
            "Airtraq": "2",
            "VividTrac": "Adult",
            "Endotracheal_Tube_Cuffed": "6.5-7.0",
            "LMA": "3-4",
            "KingTube": "3-4",
            "iGel": "3",
            "Etomidate_IV_IO": "15 mg/7.5 mL",
            "Ketamine_IV_IO": "100 mg/2 mL",
            "Succinylcholine_IV_IO": "100 mg/5 mL",
            "Rocuronium_IV_IO": "50 mg/5 mL",
            "Fentanyl_IV_IO": "50 mcg/1 mL",
            "Midazolam_IV_IO": "4 mg/0.8 mL",
            "Lorazepam_IV_IO": "2 mg/2 mL",
            "shock_1st": "110 J",
            "shock_2nd": "200 J",
            "shock_3rd": "200 J",
            "Epinephrine_1mg_10mL_IV": "0.5 mg/5 mL",
            "Atropine_IV_IO_ETT": "1 mg/10 mL",
            "Magnesium_sulfate_IV": "2 gm/ mL",
            "Epinephrine_1mg_1mL_ETT": "2.5 mg/2.5 mL",
            "Amiodarone_IV": "250 mg/5 mL",
            "Lidocaine_IV": "50 mg/2.5 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "5 mcg/min (75 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "10 mcg/min (150 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.5 mg/0.5 mL",
            "Diphenhydramine_IV_IM": "50 mg/1 mL",
            "Famotidine_IV": "20 mg/2 mL",
            "Methylprednisolone_IV": "100 mg/1.6 mL",
            "Fentanyl_IN": "85 mcg/1.7 mL",
            "Fentanyl_IV": "50 mcg/1 mL",
            "Ketorolac_IV": "24 mg/0.8 mL",
            "Tylenol_PO": "605 mg/2 tab",
            "Ibuprofen_PO": "400 mg/2 tab",
            "Midazolam_IN": "10 mg/2 mL",
            "Midazolam_IV": "5 mg/1 mL",
            "Lorazepam_IV": "2 mg/1 mL",
            "D10_IV": "180 mL"
        ],
        "orangeDot": [
            "Miller_Blade": "3",
            "Mac_Blade": "3",
            "Airtraq": "2",
            "VividTrac": "Adult",
            "Endotracheal_Tube_Cuffed": "6.5-7.0",
            "LMA": "4",
            "KingTube": "4",
            "iGel": "4",
            "Etomidate_IV_IO": "18 mg/9 mL",
            "Ketamine_IV_IO": "120 mg/2.4 mL",
            "Succinylcholine_IV_IO": "120 mg/6 mL",
            "Rocuronium_IV_IO": "60 mg/6 mL",
            "Fentanyl_IV_IO": "60 mcg/1.2 mL",
            "Midazolam_IV_IO": "4 mg/0.8 mL",
            "Lorazepam_IV_IO": "2 mg/2 mL",
            "shock_1st": "130 J",
            "shock_2nd": "200 J",
            "shock_3rd": "200 J",
            "Epinephrine_1mg_10mL_IV": "0.6 mg/6 mL",
            "Atropine_IV_IO_ETT": "1 mg/10 mL",
            "Magnesium_sulfate_IV": "2 gm/4 mL",
            "Epinephrine_1mg_1mL_ETT": "2.5 mg/2.5 mL",
            "Amiodarone_IV": "300 mg/6 mL",
            "Lidocaine_IV": "60 mg/3 mL",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "6 mcg/min (90 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "10 mcg/min (150 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.5 mg/0.5 mL",
            "Diphenhydramine_IV_IM": "50 mg/1 mL",
            "Famotidine_IV": "20 mg/2 mL",
            "Methylprednisolone_IV": "120 mg/1.9 mL",
            "Fentanyl_IN": "100 mcg/2 mL",
            "Fentanyl_IV": "60 mcg/1.2 mL",
            "Ketorolac_IV": "30 mg/1 mL",
            "Tylenol_PO": "650 mg/2 tab",
            "Ibuprofen_PO": "400 mg/2 tab",
            "Midazolam_IN": "10 mg/2 mL",
            "Midazolam_IV": "5 mg/1 mL",
            "Lorazepam_IV": "2 mg/1 mL",
            "D10_IV": "180 mL"
        ],
        "lightBlueDot": [
            "Miller_Blade": "3",
            "Mac_Blade": "3-4",
            "Airtraq": "3",
            "VividTrac": "Adult",
            "Endotracheal_Tube_Cuffed": "7.0-8.0",
            "LMA": "4-5",
            "KingTube": "4-5",
            "iGel": "4-5",
            "Etomidate_IV_IO": "30 mg/15 mL",
            "Ketamine_IV_IO": "200 mg/4 mL",
            "Succinylcholine_IV_IO": "200 mg/10 mL",
            "Rocuronium_IV_IO": "100 mg/10 mL",
            "Fentanyl_IV_IO": "100 mcg/2 mL",
            "Midazolam_IV_IO": "4 mg/0.8 mL",
            "Lorazepam_IV_IO": "2 mg/2 mL",
            "shock_1st": "200 J",
            "shock_2nd": "200 J",
            "shock_3rd": "200 J",
            "Epinephrine_1mg_10mL_IV": "1 mg/10 mL",
            "Atropine_IV_IO_ETT": "1 mg/10 mL",
            "Magnesium_sulfate_IV": "2 gm/4 mL",
            "Epinephrine_1mg_1mL_ETT": "NA",
            "Amiodarone_IV": "300 mg/6 mL",
            "Lidocaine_IV": "NA",
            "Epinephrine_Norepinephrine_gtt_IV_init_dos": "8 mcg/min (120 gtt/min)",
            "Epinephrine_Norepinephrine_gtt_IV_max_dos": "10 mcg/min (150 gtt/min)",
            "Epinephrine_1mg_1mL_IM": "0.5 mg/0.5 mL",
            "Diphenhydramine_IV_IM": "50 mg/1 mL",
            "Famotidine_IV": "20 mg/2 mL",
            "Methylprednisolone_IV": "125 mg/2 mL",
            "Fentanyl_IN": "100 mcg/2 mL",
            "Fentanyl_IV": "100 mcg/2 mL",
            "Ketorolac_IV": "30 mg/1 mL",
            "Tylenol_PO": "650 mg/2 tab",
            "Ibuprofen_PO": "400 mg/2 tab",
            "Midazolam_IN": "10 mg/2 mL",
            "Midazolam_IV": "5 mg/1 mL",
            "Lorazepam_IV": "2 mg/1 mL",
            "D10_IV": "NA"
        ],
    ]
    
    static let concentrationMap: [String: String] = [
        "Fentanyl_IN": "50 mcg/mL",
        "Fentanyl_IV": "50 mcg/mL",
        "Ketamine_IV_IO": "50 mg/mL",
        "Midazolam_IV": "5 mg/mL",
        "Midazolam_IN": "5 mg/mL",
        // Add more concentrations as needed
    ]
    
    static func getMedicationConcentration(_ itemName: String) -> String {
        return concentrationMap[itemName] ?? ""
    }
    
    static func getDosageForHeight(_ height: Double, itemName: String) -> String {
        let color = getColorForHeight(height)
        return dosageMap[color]?[itemName] ?? ""
    }
    
    static func getDosageForWeight(_ weight: Double, itemName: String) -> String {
        let color = getColorForWeight(weight)
        return dosageMap[color]?[itemName] ?? ""
    }
    
    static func getDosageDetails(_ weight: Double, itemName: String) -> (dose: String, volume: String, concentration: String) {
        let color = getColorForWeight(weight)
        let dosageInfo = dosageMap[color]?[itemName] ?? ""
        let concentration = getMedicationConcentration(itemName)
        
        // Split dosage info into dose and volume if it contains a slash
        let components = dosageInfo.components(separatedBy: "/")
        if components.count == 2 {
            let dose = components[0].trimmingCharacters(in: .whitespaces)
            let volume = components[1].trimmingCharacters(in: .whitespaces)
            return (dose: dose, volume: volume, concentration: concentration)
        }
        
        return (dose: dosageInfo, volume: "", concentration: concentration)
    }
}
